blog/protected/models/Post.php
<?php

/**
 * The followings are the available columns in table 'tbl_post':
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property string $tags
 * @property integer $status
 * @property integer $create_time
 * @property integer $update_time
 * @property integer $author_id
 */
class Post extends CActiveRecord {

    public $verifyCode;
    public $textarea;

    /**
     * Returns the static model of the specified AR class.
     * @return static the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return '{{post}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('username, text, email', 'required'),
            array('username, homepage', 'length', 'max' => 128),
            array('email', 'email'),
            array('username', 'safe', 'on' => 'search'),
            array('verifyCode', 'CaptchaExtendedValidator', 'allowEmpty' => !CCaptcha::checkRequirements()),
        );
    }

    public function attributeLabels() {
        return array(
            'id' => 'Id',
            'username' => 'Username',
            'text' => 'Text',
            'create_time' => 'Create Date',
            'email' => 'E-mail',
            'homepage' => 'Home Page',
            'verifyCode' => 'Verification Code',
            'ip' => 'IP',
            'browser' => 'Browser',
        );
    }

    /**
     * @return string the URL that shows the detail of the post
     */
    public function getUrl() {
        return Yii::app()->createUrl('post/view', array(
                    'id' => $this->id,
        ));
    }

    protected function afterFind() {
        parent::afterFind();
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('username', $this->username, true);

        return new CActiveDataProvider('Post', array(
            'criteria' => $criteria,
            'sort' => array(
                'defaultOrder' => 'create_time DESC',
            ),
            'pagination' => array(
                'pageSize' => Yii::app()->params['postsPerPage'],
            ),
        ));
    }

    /**
     * This is invoked before the record is saved.
     * @return boolean whether the record should be saved.
     */
    protected function beforeSave() {
        if (parent::beforeSave()) {
            if ($this->isNewRecord)
                $this->create_time = time();
            $this->ip = $_SERVER['REMOTE_ADDR'];
            $this->browser = $_SERVER['HTTP_USER_AGENT'];
            return true;
        } else {
            return false;
        };
    }

    /**
     * This is invoked after the record is saved.
     */
    protected function afterSave() {
        parent::afterSave();
    }

    /**
     * This is invoked after the record is deleted.
     */
    protected function afterDelete() {
        parent::afterDelete();
    }

}

blog/protected/controllers/PostController.php
<?php

class PostController extends Controller {

    private $_model;

    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CaptchaExtendedAction',
                'mode' => 'math',
            ),

            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function accessRules() {
        return array(
            array('allow', // allow all users to access 'index' and 'view' actions.
                'actions' => array('index', 'view', 'create','captcha'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated users to access all actions
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionView() {
        $post = $this->loadModel();

        $this->render('view', array(
            'model' => $post,
        ));
    }

    public function actionCreate() {
        $model = new Post;
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'post-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        if (isset($_POST['Post'])) {
            $model->attributes = $_POST['Post'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    public function actionUpdate() {
        $model = $this->loadModel();
        if (isset($_POST['Post'])) {
            $model->attributes = $_POST['Post'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    public function actionDelete() {
        if (Yii::app()->request->isPostRequest) {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(array('index'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $criteria = new CDbCriteria(array(
            'order' => 'create_time DESC',
        ));

        $dataProvider = new CActiveDataProvider('Post', array(
            'pagination' => array(
                'pageSize' => Yii::app()->params['postsPerPage'],
            ),
            'criteria' => $criteria,
        ));
        $model = new Post;
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'post-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        if (isset($_POST['preview'])) {
            $this->layout = '';
            $data = array(
                'username' => $_POST['Post']['username'],
                'email' => $_POST['Post']['email'],
                'homepage' => $_POST['Post']['homepage'],
                'text' => $_POST['Post']['text'],
            );
            echo $this->renderPartial('_view', array(
                'data' => (object) $data,
                    ), true, FALSE);
            Yii::app()->end();
        }
        if (isset($_POST['Post'])) {
            $model->attributes = $_POST['Post'];
            $model->save();

            echo $this->renderPartial('index', array(
                'dataProvider' => $dataProvider,
                'model' => !empty($model->getErrors()) ? $model : new Post,
                    ), true, FALSE);
            Yii::app()->end();
        }

        $this->render('index', array(
            'dataProvider' => $dataProvider,
            'model' => $model,
        ));
    }

    public function actionAdmin() {
        $model = new Post('search');
        if (isset($_GET['Post']))
            $model->attributes = $_GET['Post'];
        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function loadModel() {
        if ($this->_model === null) {
            if (isset($_GET['id'])) {

                $condition = '';
                $this->_model = Post::model()->findByPk($_GET['id'], $condition);
            }
            if ($this->_model === null) {
                throw new CHttpException(404, 'The requested page does not exist.');
            }
        }
        return $this->_model;
    }

    public function init() {
        // import class paths for captcha extended
        Yii::$classMap = array_merge(Yii::$classMap, array(
            'CaptchaExtendedAction' => Yii::getPathOfAlias('ext.captchaExtended') . DIRECTORY_SEPARATOR . 'CaptchaExtendedAction.php',
            'CaptchaExtendedValidator' => Yii::getPathOfAlias('ext.captchaExtended') . DIRECTORY_SEPARATOR . 'CaptchaExtendedValidator.php',
        ));
    }

}

blog/protected/views/post/_form.php
<div class="form">



    <?php
    Yii::import('ext.yii-ckeditor.CKEditorWidget');


    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'post-form',
        'enableAjaxValidation' => true,
    ));
    ?>

    <p class="note">Fields with <span class="required">*</span> are required.</p>

    <?php echo CHtml::errorSummary($model); ?>

    <div class="row">
        <?php echo $form->labelEx($model, 'username'); ?>
        <?php echo $form->textField($model, 'username', array('size' => 69, 'maxlength' => 128)); ?>
        <?php echo $form->error($model, 'username'); ?>
    </div>
    <div class="row">
        <?php echo $form->labelEx($model, 'email'); ?>
        <?php echo $form->textField($model, 'email', array('size' => 69, 'maxlength' => 128)); ?>
        <?php echo $form->error($model, 'email'); ?>
    </div>
    <div class="row">
        <?php echo $form->labelEx($model, 'homepage'); ?>
        <?php echo $form->textField($model, 'homepage', array('size' => 69, 'maxlength' => 128)); ?>
        <?php echo $form->error($model, 'homepage'); ?>
    </div>

    <div class="row">
        <?php echo $form->labelEx($model, 'text'); ?>
        <?php
        $this->widget('CKEditorWidget', array(
            'model' => $model,
            'attribute' => 'text',
            // editor options http://docs.ckeditor.com/#!/api/CKEDITOR.config
            'config' => array(
                'language' => 'ru',
            'width' => '200px',
            ),
        ));
        ?>
        <?php echo $form->error($model, 'text'); ?>
    </div>
    <?php // if($model->isNewRecord){?>
    <?php if (CCaptcha::checkRequirements()): ?>

        <div class="row">

            <div>
                <?php echo $form->labelEx($model, 'verifyCode'); ?>
                <?php $this->widget('CCaptcha'); ?>
                <?php // $this->widget('CaptchaExtendedAction'); ?>
                <?php echo $form->textField($model, 'verifyCode'); ?>
                <?php echo $form->error($model, 'verifyCode'); ?>
            </div>
            <div class="hint">Please enter the letters as they are shown in the image above.
                <br/>Letters are not case-sensitive.</div>

        <?php endif; ?>
    </div>
    <?php // }?>
    <div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

blog/protected/views/post/_view.php
<div class="post">
    <hr />
    <div class="username">
        <?php echo 'Username:' . CHtml::link(CHtml::encode($data->username), $data->url); ?>
    </div>
    <div class="email">
        <?php echo 'E-mail:' . $data->email; ?>
    </div>
    <div class="homepage">
        <?php echo 'Homepage:' . $data->homepage; ?>
    </div>
    <div class="text">
         <?php
         echo 'Text:' . $data->text;
//          echo $data->text;
        ?>
    </div>
</div>

blog/protected/views/post/admin.php
<?php
$this->breadcrumbs = array(
    'Manage Posts',
);
?>
<h1>Manage Posts</h1>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        'id',
        'username',
        'email',
        'homepage',
        'ip',
        'browser',
        array(
            'name' => 'create_time',
            'type' => 'date',
            'filter' => false,
        ),
        array(
            'class' => 'CButtonColumn',
        ),
    ),
));
?>

blog/protected/views/post/create.php
<?php
$this->breadcrumbs=array(
	'Create Post',
);
?>
<h1>Create Post</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog/protected/views/post/index.php
<div id="list">
    <?php
    Yii::import('ext.yii-ckeditor.CKEditorWidget');

//    $js = Yii::app()->getClientScript();
//    $js->registerScriptFile('//cdn.ckeditor.com/4.4.7/basic/ckeditor.js');
//    $js->registerScript('js2', "CKEDITOR.replace('Post_text',{width:510});", CClientScript::POS_LOAD);

    $this->widget('zii.widgets.CListView', array(
        'dataProvider' => $dataProvider,
        'itemView' => '_view',
        'template' => "{items}\n{pager}",
    ));
    ?>

    <?php if (!empty($model)): ?>
        <div class="form">

            <hr />
            <?php
            $form = $this->beginWidget('CActiveForm', array(
                'id' => 'post-form',
                'enableAjaxValidation' => true,
            ));
            ?>

            <p class="note">Fields with <span class="required">*</span> are required.</p>

            <?php echo CHtml::errorSummary($model); ?>

            <div class="row">
                <?php echo $form->labelEx($model, 'username'); ?>
                <?php echo $form->textField($model, 'username', array('size' => 69, 'maxlength' => 128)); ?>
                <?php echo $form->error($model, 'username'); ?>
            </div>
            <div class="row">
                <?php echo $form->labelEx($model, 'email'); ?>
                <?php echo $form->textField($model, 'email', array('size' => 69, 'maxlength' => 128)); ?>
                <?php echo $form->error($model, 'email'); ?>
            </div>
            <div class="row">
                <?php echo $form->labelEx($model, 'homepage'); ?>
                <?php echo $form->textField($model, 'homepage', array('size' => 69, 'maxlength' => 128)); ?>
                <?php echo $form->error($model, 'homepage'); ?>
            </div>

            <div id="text" class="row">
                <?php
                echo $form->labelEx($model, 'text');
                $this->widget('CKEditorWidget', array(
                    'model' => $model,
                    'attribute' => 'text',
                    'id' => 'text',
                    // editor options http://docs.ckeditor.com/#!/api/CKEDITOR.config
                    'config' => array(
                        'language' => 'ru',
                        'width' => '510',
                    ),
                ));
                ?>

            </div>

            <?php 
           
            if (CCaptcha::checkRequirements()): ?>

                <div class="row">
                    <?php echo $form->labelEx($model, 'verifyCode'); ?>
                    <div>
                        <?php $this->widget('CCaptcha'); ?>
                        <?php // $this->widget('CaptchaExtendedAction'); ?>
                        <?php echo $form->textField($model, 'verifyCode'); ?>
                        <?php echo $form->error($model, 'verifyCode'); ?>
                    </div>
                    <div class="hint">Please enter the letters as they are shown in the image above.
                        <br/>Letters are not case-sensitive.</div>

                <?php endif; ?>
            </div>
            <div id="button_create" class="row buttons">
                <?php
                echo CHtml::ajaxSubmitButton('AddPost', Yii::app()->createUrl('post/index'), array(
                    'type' => 'POST',
                    'update' => '#list',
                        ), array(
                    'type' => 'submit',
                    'id' => 'button_create',
                    'name' => 'Submit'
                ));
                ?> 
            </div>

            <?php
            $this->endWidget();
            echo CHtml::button('PreviewPost', array('id' => 'button_preview'));
            ?>
            <hr />

        </div><!-- form -->

        <div id="preview">

        </div>
        <script>
            $(function () {

                $(document).on('click', '#button_preview', function (e) {
                    e.preventDefault();
                    var texteditor = CKEDITOR.instances['Post_text'].getData();
                    document.getElementById('Post_text').value = texteditor
                    var form = $('#post-form');
                    console.log(form.serialize());
                    $.ajax({
                        type: "POST",
                        url: form.attr('action'),
                        data: form.serialize() + '&preview=true',
                        success: function (msg) {
                            $('#preview').html(msg);

                        }
                    });
                });
            });
        </script>
        <script>
            $(function () {

                $(document).on('focus', '#button_create', function (u) {
                    u.preventDefault();
                    var texteditor = CKEDITOR.instances['Post_text'].getData();
                    document.getElementById('Post_text').value = texteditor
                    var form = $('#post-form');
                    console.log(form.serialize());

                });
            });
        </script>
    <?php endif; ?>
</div>

blog/protected/views/post/update.php
<?php
$this->breadcrumbs=array(
	$model->username=>$model->url,
	'Update',
);
?>

<h1>Update <i><?php echo CHtml::encode($model->username); ?></i></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

blog/protected/views/post/view.php
<?php
$this->breadcrumbs=array(
	$model->username,
);
$this->pageTitle=$model->username;
?>

<?php $this->renderPartial('_view', array(
	'data'=>$model,
)); ?>